=== Quodatum/app-doc/src/static/schemas/components.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="components">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="cmp" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="cmp">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="runat" type="xs:string" />
				<xs:element name="tagline" type="xs:string" />
				<xs:element name="home" type="xs:string" />
				<xs:element name="licence" type="xs:string" />
				<xs:element name="release" type="releaseComplexType" />
				<xs:element name="depends" type="xs:string" />
			</xs:choice>
			<xs:attribute use="required" name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="releaseComplexType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="local">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute use="optional" name="type" type="xs:string">
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="cdn">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute use="optional" name="type" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute use="required" name="version" type="xs:string"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== Quodatum/app-doc/src/doc/data/doc/components.xml
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="components.xsd">
	<cmp name="angular-tree-control">
		<runat>browser</runat>
		<tagline>The AngularJS tree component.
		</tagline>
		<home>http://wix.github.io/angular-tree-control/</home>
		<licence>MIT</licence>
		<release version="0.2.0">
			<local type="css">lib/angular-tree-control/0.2.0/css/tree-control.css
			</local>
			<local type="js">lib/angular-tree-control/0.2.0/tree-control.js
			</local>
		</release>
	</cmp>
	<cmp name="jquery">
		<runat>browser</runat>
		<tagline>jQuery is a fast, small, and feature-rich JavaScript library.
			It makes things like HTML document traversal and manipulation, event
			handling, animation, and Ajax much simpler with an easy-to-use API
			that works across a multitude of browsers.
		</tagline>
		<home>http://jquery.com/</home>
		<licence>MIT</licence>
		<release version="2.0.2">
			<cdn>//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js</cdn>
		</release>
	</cmp>

	<cmp name="twitter-bootstrap">
		<runat>browser</runat>
		<home>http://getbootstrap.com/</home>
		<tagline>The most popular front-end framework for developing
			responsive, mobile first projects on the web.
		</tagline>
		<licence>Apache v2.0</licence>
		<release version="3.3.1">
			<cdn type="css">//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.css
			</cdn>
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js
			</cdn>
		</release>
	</cmp>
	<cmp name="twitter-bootstrap-css">
		<runat>browser</runat>
		<home>http://getbootstrap.com/</home>
		<tagline>The most popular front-end framework for developing
			responsive, mobile first projects on the web.
		</tagline>
		<licence>Apache v2.0</licence>
		<release version="3.3.4">
			<cdn type="css">//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.css
			</cdn>
		</release>
	</cmp>

	<cmp name="moment">
		<runat>browser</runat>

		<home>http://momentjs.com/</home>
		<tagline>A javascript date library for parsing, validating,
			manipulating, and formatting dates.
		</tagline>
		<licence>MIT</licence>
		<release version="2.6.0">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/moment.js/2.6.0/moment-with-langs.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angular-moment">
		<runat>browser</runat>

		<home>https://github.com/urish/angular-moment</home>
		<tagline>Angular.JS directives for Moment.JS (timeago alternative)
		</tagline>
		<depends>moment</depends>
		<depends>angularjs</depends>
		<licence>MIT</licence>
		<release version="0.7.0">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/angular-moment/0.7.0/angular-moment.min.js
			</cdn>
		</release>
	</cmp>
	<cmp name="scrollTo">
		<runat>browser</runat>
		<home>https://github.com/khalilravanna/scrollTo</home>
		<tagline>A simple scrollTo directive using $anchorScroll. The
			directive also catches the locationChangeStart event thus preventing
			a page reload.
		</tagline>
		<depends>angularjs</depends>
		<licence>MIT</licence>

	</cmp>
	<cmp name="lodash">
		<runat>browser</runat>
		<home>http://lodash.com/</home>
		<tagline>A utility library delivering consistency, customization,
			performance, &amp; extras.</tagline>
		<licence>MIT</licence>
		<release version="2.4.1">
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angularjs">
		<runat>browser</runat>

		<home>https://angularjs.org/</home>
		<tagline>HTML enhanced for web apps!</tagline>
		<licence>MIT</licence>
		<release version="1.2.14">
			<cdn>//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angular-ui-bootstrap">
		<runat>browser</runat>
		<home>http://angular-ui.github.io/bootstrap/</home>
		<tagline>Bootstrap components written in pure AngularJS by the
			AngularUI Team
		</tagline>
		<depends>angularjs</depends>
		<release version="0.12.0">
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.12.0/ui-bootstrap-tpls.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="d3">
		<runat>browser</runat>
		<home>http://d3js.org/</home>
		<tagline>Data driven documents
		</tagline>
		<release version="3.4.6">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/d3/3.4.6/d3.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angular-charts">
		<runat>browser</runat>

		<home>http://chinmaymk.github.io/angular-charts/</home>
		<tagline>angular directives for commonly used d3 charts
		</tagline>
		<depends>angularjs</depends>
		<depends>d3</depends>
		<release version="0.2.1">
			<local>lib/angular-charts/0.2.1/angular-charts.min.js</local>
		</release>
	</cmp>

	<cmp name="ngStorage">
		<runat>browser</runat>
		<home>https://github.com/gsklee/ngStorage</home>
		<tagline>localStorage and sessionStorage done right for AngularJS.
		</tagline>
		<depends>angularjs</depends>
		<release version="0.3.0">
			<local>lib/ngStorage/0.3.0/ngStorage.js</local>
		</release>
	</cmp>

	<cmp name="angular-hotkeys">
		<runat>browser</runat>

		<home>http://chieffancypants.github.io/angular-hotkeys/</home>
		<tagline>Configuration-centric keyboard shortcuts for your angular
			apps
		</tagline>
		<depends>angularjs</depends>
		<release version="1.2.0">
			<local>lib/angular-hotkeys/1.2.0/hotkeys.min.js</local>
		</release>
		<release version="1.4.5">
			<cdn type="css">//cdnjs.cloudflare.com/ajax/libs/angular-hotkeys/1.4.5/hotkeys.css
			</cdn>
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/angular-hotkeys/1.4.5/hotkeys.js
			</cdn>
		</release>
	</cmp>

	<cmp name="ng-google-chart">
		<runat>browser</runat>
		<home>http://bouil.github.io/angular-google-chart/#/fat</home>
		<tagline>Google Chart Tools AngularJS Directive Module
		</tagline>
		<depends>angularjs</depends>
		<release version="0.0.9">
			<local>lib/googlechart/0.0.9/ng-google-chart.js</local>
		</release>
	</cmp>

	<cmp name="saxon-he">
		<runat>basex</runat>
		<home>http://www.saxonica.com/welcome/welcome.xml</home>
		<tagline>basic XSLT 2.0 processor
		</tagline>
		<depends>java</depends>
	</cmp>

	<cmp name="async">
		<runat>browser</runat>
		<home>https://github.com/caolan/async</home>
		<tagline>Async utilities for node and the browser</tagline>
		<release version="0.8.0">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/async/0.8.0/async.js</cdn>
		</release>
	</cmp>

	<cmp name="stacktrace">
		<runat>browser</runat>
		<home>http://www.stacktracejs.com/</home>
		<tagline>Framework-agnostic, micro-library for getting
			stack traces in
			all web browsers.
		</tagline>
		<release version="0.6.0">
			<cdn>lib/stacktrace/0.6.0</cdn>
		</release>
	</cmp>

	<cmp name="oci.treeview">
		<runat>browser</runat>
		<home>https://github.com/objectcomputing/oci.treeview</home>
		<tagline>AngularJS tree directive with subdirective for extending node
			behavior
		</tagline>
		<depends>angularjs</depends>
		<release version="2040305">
			<local type="js">lib/oci.treeview/2040305/treeview.min.js</local>
			<local type="css">lib/oci.treeview/2040305/treeview.css</local>
		</release>
	</cmp>

	<cmp name="restangular">
		<runat>browser</runat>
		<home>https://github.com/mgonto/restangular</home>
		<tagline>AngularJS service to handle Rest API Restful Resources
			properly and easily
		</tagline>
		<depends>angularjs</depends>
		<depends>lodash</depends>
		<release version="1.3.1">
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="FileSaver">
		<home>https://github.com/eligrey/FileSaver.js/</home>
		<tagline>An HTML5 saveAs() FileSaver implementation</tagline>
		<release version="">
			<local type="js">lib/FileSaver.js</local>
		</release>
	</cmp>

	<cmp name="ace">
		<home>http://ace.c9.io/</home>
		<licence>BSD</licence>
		<tagline>Ace is an embeddable code editor written in JavaScript.
		</tagline>
		<release version="01.08.2014">
			<local>lib/ace/01.08.2014</local>
		</release>
	</cmp>

	<cmp name="ui-ace">
		<home>https://github.com/angular-ui/ui-ace</home>
		<release version="01.08.2014">
			<cdn>lib/ace/01.08.2014</cdn>
		</release>
	</cmp>

	<cmp name="toastr">
		<home>http://codeseven.github.io/toastr/</home>
		<release version="2.0.1">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angular-flashr">
		<home>https://github.com/TylerGarlick/angular.flashr</home>
		<tagline>Flashr is a library that simulates flashing in rails in
			AngularJS.
			Essentially, it allows you to post notifications via the
			simple api.
		</tagline>
		<depends>angularjs</depends>
		<release version="2.0.1">
			<cdn type="js">//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="angular-ya-treeview">
		<home>https://github.com/ca77y/angular-ya-treeview</home>
		<tagline>Yet Another Treeview for AngularJS</tagline>
		<depends>angularjs</depends>
		<release version="0.2.1">
			<cdn>//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.min.js
			</cdn>
		</release>
	</cmp>

	<cmp name="font-awesome">
		<runat>browser</runat>
		<home>http://fortawesome.github.io/Font-Awesome/</home>
		<tagline>Font Awesome gives you scalable vector icons that can
			instantly be customized
			â€” size, color, drop shadow, and anything that
			can be done with the
			power of CSS.
		</tagline>
		<release version="4.1.0">
			<cdn>//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
			</cdn>
		</release>
	</cmp>

	<cmp name="satellizer">
		<runat>browser</runat>
		<home>https://github.com/sahat/satellizer</home>
		<tagline>Satellizer is a simple to use, end-to-end, token-based
			authentication module
			for AngularJS with built-in support for Google,
			Facebook, LinkedIn,
			Twitter authentication providers, plus Email and
			Password sign-in
			method.
		</tagline>
		<release version="0.7.0">
